#
#
# This file is here to wait for Symfony 5.0 & notifier config in FrameworkBundle
parameters:

    chat_transport: '%env(SLACK_DSN)%'
    email_transport: '%env(MAILER_DSN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Notifier\NotifierInterface:
        class: Symfony\Component\Notifier\Notifier
        arguments:
            $channels:
                chat: '@Symfony\Component\Notifier\Channel\ChatChannel'
                email: '@Symfony\Component\Notifier\Channel\EmailChannel'

    notifier.chat_transport:
        class: Symfony\Component\Notifier\Transport
        factory: ['Symfony\Component\Notifier\Transport', 'fromDsn']
        arguments: [ '%chat_transport%' ]

    Symfony\Component\Notifier\Channel\ChatChannel:
        arguments:
            $transport: '@notifier.chat_transport'

    notifier.email_transport:
        class: Symfony\Component\Notifier\Transport
        factory: ['Symfony\Component\Mailer\Transport', 'fromDsn']
        arguments: [ '%email_transport%' ]

    Symfony\Component\Notifier\Channel\EmailChannel:
        arguments:
            $transport: '@notifier.email_transport'
            $from: '%notification_mail_from%'

    Symfony\Component\Notifier\Channel\ChannelPolicyInterface:
        class: Symfony\Component\Notifier\Channel\ChannelPolicy
        arguments:
            $policy: '%notification_channel_policy%'
