api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Model']

    enable_swagger_ui: false
    enable_re_doc: false

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
