framework:
    notifier:
        texter_transports: ~
        chatter_transports:
            slack: '%env(SLACK_DSN)%'

        channel_policy:
            urgent: ['chat/slack', email]
            high:   ['chat/slack', email]
            medium: ['chat/slack']
            low:    ['chat/slack']
