security:
    providers:
        users:
            entity:
                class: 'App\Model\User'
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^(/api/connect/google|/admin)
            stateless: false
            anonymous: true
            guard:
                provider: users
                authenticators:
                    - App\Security\GoogleAuthenticator

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        api_doc:
            pattern:   ^/api/docs$
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/api/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs,           roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,                roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,              roles: ROLE_ADMIN }
