version: '3.7'

services:
    php:
        env_file: .env
        ports:   [ '8080:8080' ]
        volumes: [ '.:/app' ]

    web:
        ports:   [ '80:80', '443:443' ]
        volumes: [ '.:/app' ]

    database:
        ports:   [ '5432:5432' ]
