version: '3.7'

services:
    php:
        networks:   [ heimdall ]
        build:      { target: php, context: . }
        depends_on: [ database ]

    web:
        networks:   [ heimdall ]
        build:      { target: nginx, context: . }
        depends_on: [ php ]

    database:
        image:    postgres:11-alpine
        volumes:  [ 'database-data:/var/lib/postgresql/data' ]
        networks: [ heimdall ]
        environment:
            - POSTGRES_DB=heimdall
            - POSTGRES_USER=heimdall
            - POSTGRES_PASSWORD=heimdall

volumes:
    database-data: ~

networks:
    heimdall: ~
