version: '3.7'

services:
    php:
        env_file: .env
        volumes: [ '.:/app' ]

    web:
        ports:   [ '80:80' ]
        volumes: [ '.:/app' ]

    database:
        ports:   [ '5432:5432' ]
