version: '3.7'

services:
    php:
        networks:   [ heimdall ]
        build:      { target: php, context: . }
        depends_on: [ database ]

    web:
        networks:   [ heimdall ]
        build:      { target: nginx, context: . }
        depends_on: [ php, mercure ]

    mercure:
        image:    dunglas/mercure
        networks: [ heimdall ]
        environment:
            - JWT_KEY=!ChangeMe!
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - PUBLISH_ALLOWED_ORIGINS=http://localhost

    database:
        image:    postgres:11-alpine
        volumes:  [ 'database-data:/var/lib/postgresql/data' ]
        networks: [ heimdall ]
        environment:
            - POSTGRES_DB=heimdall
            - POSTGRES_USER=heimdall
            - POSTGRES_PASSWORD=heimdall



volumes:
    database-data: ~

networks:
    heimdall: ~
