version: '3.7'

services:
    php:
        env_file: [ .env, .env.local ]
        ports:    [ '8080:8080' ]
        volumes:  [ '.:/app' ]
        depends_on:
          - smtp

    web:
        ports:   [ '80:80', '443:443' ]
        volumes: [ '.:/app' ]

    database:
        ports:   [ '5432:5432' ]

    smtp:
        image:    mailhog/mailhog
        networks: [ heimdall ]
        ports:    ['8025:8025']

    cron:
        env_file: [ .env, .env.local ]
        volumes:  [ '.:/app' ]
        depends_on:
            - smtp
