api_connect_google_check:
    path: /api/connect/google/check

connect_google_check:
    path: /login/google/check
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:     { template: index.html.twig, uri: '' }

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

index:
    path:         /{uri}
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:     { template: index.html.twig, uri: '' }
    requirements: { uri: .* }
