index:
    path:         /{uri}
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:     { template: index.html.twig, uri: '' }
    requirements: { uri: .* }
